import { Button, TextField, Typography } from "@mui/material";
import React, { useState } from "react";
import { Controller, useForm } from "react-hook-form";
import * as Yup from "yup";
import { yupResolver } from "@hookform/resolvers/yup";
import { Metadata } from "next";
import LoginForm from "@/app/_components/pages/login/LoginForm";

export const metadata: Metadata = {
  title: "Login page",
  description: "Generated by create next app",
};

type Props = {};

type User = {
  username: string;
  password: string;
  type?: string;
};

const defaultValues: User = {
  username: "",
  password: "",
};

export default function LoginPage({}: Props) {
  return <LoginForm />;
}
