GET http://localhost:8081/api/v1/Product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGb3IgVGVzdGluZyIsImlkIjoiMSIsInVzZXJuYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTcwMzMxODU1OSwiaXNzIjoiQ29kZU1vYmlsZXMgTHRkIiwiYXVkIjoiaHR0cDovL2NvZGVtb2JpbGVzLmNvbSJ9._ANIvrjjlyM8KjaisLIQFMTlNh0hBoD5pgXg3W9WC-U